apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
#define the cluster
metadata:
  #user-defined name of the cluster; string
  name: beta-tkg-01
  #kubernetes namespace for the cluster; string
  namespace: ns01
#define the desired state of cluster
spec:
  #specify the cluster network; required, there is no default
  clusterNetwork:
    #network ranges from which service VIPs are allocated
    services:
      #CAUTION: must not overlap with Supervisor
      cidrBlocks: ["10.96.0.0/12"]
    #network ranges from which Pod networks are allocated
    pods:
      #CAUTION: must not overlap with Supervisor
      cidrBlocks: ["192.168.156.0/20"]
    serviceDomain: cluster.local
  topology:
    class: tanzukubernetescluster
    version: v1.28.8---vmware.1-fips.1-tkg.2
    controlPlane:
      replicas: 1
      metadata:
        annotations:
          run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 3
          metadata:
            annotations:
              run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
    variables:
      - name: vmClass
        value: best-effort-large
      - name: storageClass
        value: vsan-default-storage-policy
      - name: defaultStorageClass
        value: vsan-default-storage-policy
      - name: nodePoolVolumes
        value:
          - name: containerd
            capacity:
              storage: 20Gi
            mountPath: /var/lib/containerd
            storageClass: vsan-default-storage-policy
          - name: kubelet
            capacity:
              storage: 20Gi
            mountPath: /var/lib/kubelet
            storageClass: vsan-default-storage-policy
